# Generated by Django 3.0 on 2021-05-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpLab_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='0', max_length=16),
            preserve_default=False,
        ),
    ]
